title: Krabičkový blog
description: Tipy na dárky, seznámení se značkami, kam za nákupy, jak vybírat dárky.

url: http://blog.krabickanamiru.cz
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Zpět na web
   url: http://www.krabickanamiru.cz/
 - title: Příběhy značek
   url: /pribehy-znacek
 - title: Tipy na dárky
   url: /tipy-na-darky

exclude:
 - vendor/bundle

google_analytics: "UA-48819928-2"
