title: Krabičkový blog
description: Tipy na dárky, seznámení se značkami, kam za nákupy, jak vybírat dárky.

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Zpět na web
   url: http://www.krabickanamiru.cz/
 - title: Příběhy značek
   url: /about
 - title: Tipy na dárky
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-48819928-2"
